
$("#dashboard .news").html("<img style='max-width:600px;' src='https://f.cloud.github.com/assets/706/2367662/0596dbc6-a771-11e3-94ae-8eb7b8a68556.jpg' />")

// $('#header .site-logo img')
//   .css('width', '97px')
//   .css('height', '80px')
//   .css('margin-top', '-15px')
//   .attr('src', '//bit.ly/ghD24e')

// // $("body").append("<style> #userbox #notifications .unread_count { display: none !important; } </style>")
// // $("body").append("<style>body {zoom: 99%;}</style>")
// // $("body").append("<style>.pagehead > ul.tabs li a .counter {font-size: 11px; line-height: 14px;}</style>")
// // $("body").append("<style>.subnav-bar ul.subnav .counter {font-size: 11px; padding-top: 2px;}</style>")

// // 'https://github.com/notifications'

// // Generated by CoffeeScript 1.3.3
// // $(document).on('navigation:keydown', '.js-notification', function(event) {
// //   var link;
// //   switch (event.hotkey) {
// //     case 'o':
// //       link = $(this).find('.js-notification-target');
// //       link.click();
// //       window.open(link.attr('href'), '_blank');
// //       return false;
// //   }
// // });

// $('.js-notification').keydown(function (e) {
//   console.log('keydown', e)

//   var keyCode = e.keyCode || e.which;
//   var link;

//   console.log('key', keyCode)

//   switch (keyCode) {
//     case 13: //enter
//     case 32: //space
//       link = $(this).find('.js-notification-target');
//       link.click();
//       window.open(link.attr('href'), '_blank');
//       return false;
//   }
// });
